# ConfigMap 정의: 초기화 SQL 스크립트를 포함
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init-script
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS app;
    GRANT ALL PRIVILEGES ON app.* TO 'root'@'%' IDENTIFIED BY 'k8s12345';
    FLUSH PRIVILEGES;
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-pv
  labels:
    type: local
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 500Mi
  persistentVolumeReclaimPolicy: Retain
  storageClassName: db-storage
  hostPath:
    path: /home/ubuntu/advanced/cicd/data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Mi
  storageClassName: db-storage
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  labels:
    app: mysql
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  selector:
    app: mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql-container
          image: mysql
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: k8s12345
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysqldata
            - name: mysql-init-script-volume
              mountPath: /docker-entrypoint-initdb.d/
      volumes:
        - name: mysqldata
          persistentVolumeClaim:
            claimName: db-pvc
        - name: mysql-init-script-volume
          configMap:
            name: mysql-init-script
